# Generated by Django 5.0.6 on 2024-10-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_Id',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
