# Generated by Django 5.0.6 on 2024-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_items_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_Id',
            field=models.IntegerField(unique=True),
        ),
    ]
